### ISSUE TITLE
File EmailProvider is broken

### ISSUE THREAD

**Issue by gldraphael** [losol/EventManagement#101]
The `FileEmailWriter` class lacks an implementation for the `SendEmailAsync(email, subject, message, attachment)` overload.

https://github.com/losol/EventManagement/blob/ae925c986e50db77a52636d25bd02c0269e6e2e5/src/EventManagement.Services/Messaging/Email/FileEmailWriter.cs#L42

This overload is used in the Web app's `ApplicationEmailSender` and its subclasses, which results in an `NotImplementedException` every time the application tries to send an email.

**Solutions:**

* Remove the `FileEmailWriter` and its options if it's not required or there's no enough value in supporting it.
* Implement the method either by ignoring the attachment or by saving it to the filesystem.

**Comment by losviko** [comment]
I think we could just ignore the attachement.

**Comment by losviko** [comment]
Fixed this.
