### ISSUE TITLE
Add some global variables

### ISSUE THREAD

**Issue by losviko** [losol/EventManagement#115]
It would be cool to have some global variables, some of the should be set from configuration. 
As a startit could be: 
* Site.Title (from configuration Site__Title)
* Site.Description (from configuration Site__Description)
* Site.ApiBaseUrl (from Site__ApiBaseUrl)

**Comment by gldraphael** [comment]
What is the point of having an `ApiBaseUrl`?

**Comment by losviko** [comment]
@gldraphael I am considering splitting out all apis to a separate project.... It might be hosted on a different instance as well...
