### ISSUE TITLE
Add registration options

### ISSUE THREAD

**Issue by losviko** [losol/EventManagement#167]
We should split orders  and invoices. There should be only one order for each registration. The order should be updated at all times, and be the source of product user listings. There may be several invoices for each registration.

**Comment by losviko** [comment]
Possibly a manual migration to single order pr registration, and with multiple invoices pr order.

**Comment by gldraphael** [comment]
Orders being transactional data should be immutable. So this is a bad idea IMO.

**Comment by losviko** [comment]
Okay, closing this.
