### ISSUE TITLE
Add event listing for use on front page

### ISSUE THREAD

**Issue by losviko** [losol/EventManagement#20]
Should be sorted by year/month. Should include ongoing events

2018:
Jan
* Date start-Date End: Event title, event description
* Date start only if date start = Date end. Event title, event description. 

Feb
* Date start-Date End: Event title, event description
* Date start only if date start = Date end. Event title, event description.

**Comment by gldraphael** [comment]
@losviko Could you have a look at #64 ?

**Comment by losviko** [comment]
@gldraphael Thanks for this, I had to manually refactor this. I guess you have seen allready.
