### ISSUE TITLE
Customer name is lost when editing order

### ISSUE THREAD

**Issue by gldraphael** [losol/EventManagement#222]
Steps to reproduce:

1. Go to an editable order in `/Admin/Orders/Details/x` and click on _Endre_ under _ Betalingsinformasjon_.
1. The Customer Name that was available in the `/Admin/Orders/Details/x` will be missing here. (This is because the customer name was actually missing, and the previous page was showing the Participant Name since the customer name was null.)
1. Now make a change to someother field eg. email. It'll show a success prompt.
1. Scroll down and click on the _Vis ordre_ button.
1. The participant name that was previously shown in the Customer name field will no longer be shown there.

**Comment by losviko** [comment]
Thanks!
