### ISSUE TITLE
Impossible to add orders for registrations without orders

### ISSUE THREAD

**Issue by losviko** [losol/EventManagement#240]
It should be possible to add orders for users with registrations with no orders. 

Sequence to reproduce: 
1. Admin adds user to event from /Admin/Events/AddRegistration/x page
1. Admin presses edit products (Endre -> Produkter)
1. Nothing happens

Expected behavoiur: 
1. Products modal shows with 0 an all products
1. When saving a new order is created.

**Comment by gldraphael** [comment]
Cannot reproduce this.

**Comment by losviko** [comment]
Havent reproduced this myself. Closing
