### ISSUE TITLE
Admin UI: Order management

### ISSUE THREAD

**Issue by losviko** [losol/EventManagement#47]
We should start on a order management service and ui. 

- [x] View all orders in list, preferably with a search
- [x] View order details
- [x] Edit order details (customer information, comments)
- [x] Edit orderlines (quantity, price)
- [x] Add order line to existing order
- [x] Delete existing order lines (including order lines for mandatory products)
- ~Add new order for user~ (will be done separately)

Methods I would like to see: 
* GetOrder(int orderId)
* GetLatestOrders(int count), GetLastetOrders(int count, int offset)
* GetOrdersForUser(string email)
* AddOrderLine(int orderId, OrderLine orderLine)
* GetOrdersForProduct(productId)

**Comment by gldraphael** [comment]
I don't think orders should be editable.
