### ISSUE TITLE
Generating certificates for users attending courses

### ISSUE THREAD

**Issue by losviko** [losol/EventManagement#55]
As a course admin I could generate a certificate/diploma for all users have finished a course and send each participant their own certificate as an pdf attachment so that participant receives certificate. 

As a course participant I could view the course certificate in a web browser by the url I get so that I could view or share the certificate.

As a course particiapnt I could export an pdf with my certificate, or get it as an attachment to an email, so that I could archive my certificate.

Template:
https://codepen.io/losol/pen/ddxBLy

**Comment by losviko** [comment]
draft certificate class
```
public class CourseCertificate
    {
        // Certificate info and description
        [Required]
        public int CourseCertificateId { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CertificateGuid { get; set; }

        [Required]
        public string Title {get;set;} 

        [Required]
        public string Description {get;set;}

        // The person receiving the certificate
        public string RecipientUserId { get; set; }
        public string RecipientName {get;set;}

        // The organization issuing the certificate
        public int IssuerOrganizationId {get;set;} 
        public string IssuerOrganizationName {get;set;}
        public string IssuerOrganizationLogoUrl {get;set;}

        // The person from the issuing organization which is approving the certificate
        public string IssuerUserId {get;set;}
        public string IssuerPersonName {get;set;}


    }
```

**Comment by losviko** [comment]
And new organizations classes.. Organizations has many to many relationship with users. 

```
public class Organization
{
        public int OrganizationId { get; set; }
        
        [Required]
        public string Name {get;set;} 
```

**Comment by gldraphael** [comment]
Do organizations also share a one-to-many relationship with events? (One org can have multiple events?)

**Comment by gldraphael** [comment]
@losviko can we move the Organization to a separate PR? This PR could merely focus on certificate generation.

**Comment by gldraphael** [comment]
Note: PR #66 does NOT add organization information or event information (_Events finished PASSED (WITH DATES)_) to the certificate.

**Comment by losviko** [comment]
Related #80

**Comment by losviko** [comment]
Closing this as solved now.
