### ISSUE TITLE
Mark persons as attended in the participants page

### ISSUE THREAD

**Issue by losviko** [losol/EventManagement#69]
As a course admin I could mark registered users as attended so that I could keep track on who has attended. 

It should happen on this page, and preferably without postback of the whole page. 
/Admin/Events/Participants?id=1

**Comment by gldraphael** [comment]
@losviko Should it also be possible to remove attendance for a user?

**Comment by gldraphael** [comment]
Should date-time checks be added? So that attendance can only be marked during the event and for a limited amount of time after the event?

**Comment by losviko** [comment]
@gldraphael It should be possible to de-attend a registrant, yes.

And for the second question - no checks for now.

**Comment by losviko** [comment]
@gldraphael Could we add some visual indication on the button that the user is marked as attended? Change colour to btn-secondary for example?

**Comment by gldraphael** [comment]
Sure, we should also use separate texts, don't you think?
