### ISSUE TITLE
Add users to products in the list page

### ISSUE THREAD

**Issue by losviko** [losol/EventManagement#70]
As a course admin I could add users to a product so that I could get more users on the products. 

On this page: https://kursinord.no/Admin/Products/x  the admin could add users to a product. If there is an order for the user on the actual event which is not invoiced, the product should just be added to the order. If there is no order, or the previous order is invoiced - we should create a new order.

**Comment by losviko** [comment]
@gldraphael  We are dropping the select search box for now, and just adding by user email.

**Comment by gldraphael** [comment]
It should only accept users that already have a registration for the event. Correct?
