### ISSUE TITLE
Certificate generation/download fails

### ISSUE THREAD

**Issue by losviko** [losol/EventManagement#80]
After building the Node folder, is not deployed to Azure hosting. Getting this error/exception: 

An unhandled exception has occurred: Cannot find module 'D:\home\site\wwwroot\Node\writeToPdf'
 Error: Cannot find module 'D:\home\site\wwwroot\Node\writeToPdf' at Function.Module._resolveFilename (module.js:469:15)

**Comment by losviko** [comment]
Seems like the app looks for the writetopdf.js in the wwwroot/Node folder, however the file is on the root level (D:\home\site\Node\):

```
An unhandled exception has occurred: Cannot find module 'html-pdf'
 Error: Cannot find module 'html-pdf' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (D:\home\site\wwwroot\Node\writeToPdf.js:1:73)
```

**Comment by gldraphael** [comment]
> Error: Cannot find module 'html-pdf'

`html-pdf` is a dependency that needs to be installed.
`npm install` needs to be run on deployment.

Check the `package.json` file:

https://github.com/losol/EventManagement/blob/9faa3a44ed243b8c0d7a4b464a0d8683d3c719a7/src/EventManagement.Web/package.json#L11
